redWine/urls.py
from django.conf.urls import patterns, include, url
from redWine.views import redWine_home, redWine_com
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^(\w+)/$', redWine_com),
	url(r'^$', redWine_home),
    (r'^admin/', include(admin.site.urls)),
    #(r'accounts/login/',include(admin.site.urls)),
    #url (r'^/$', redWine_home),
)

redwine/urls.py
from django.conf.urls import include
from redwine.views import redwine_home, redwine_com, redwine_top
from django.contrib import admin
from django.urls import re_path

admin.autodiscover()

urlpatterns = [
    re_path(r"^top/$", redwine_top),
    re_path(r"^([\w-]+)/$", redwine_com),
    re_path(r"^$", redwine_home),
]

redwine/models.py
from django.db import models
from django.db.models import Count
from django.conf import settings
from django.db.models.signals import post_save
#from django.contrib.auth import get_user_model


class Penalty(models.Model):
    
    to =        models.ForeignKey(settings.AUTH_USER_MODEL, related_name='penalties', on_delete=models.CASCADE)
    giver =     models.ForeignKey(settings.AUTH_USER_MODEL, related_name='penaltygiver', on_delete=models.CASCADE)
    amount =    models.PositiveIntegerField()
    committee = models.CharField(max_length=60)
    reason =    models.CharField(max_length=100)
    date =      models.DateTimeField(auto_now=True)
    deleted =   models.BooleanField(default=False)
    item =      models.CharField(default="wine", max_length=30)
    item_name = models.CharField(default="vin", max_length=30)

    def __unicode__(self):
        return u'%s - %s' % (self.amount, self.to)

    class Meta:
        ordering = ['-date']
        get_latest_by = 'date'

redwine/forms.py
from django import forms
from .models import Penalty

class newPenaltyForm(forms.ModelForm):
    reason = forms.CharField(help_text="Begrunnelse for vinstraff")
    amount = forms.IntegerField( initial=0)
    giver = forms.IntegerField(widget=forms.HiddenInput())
    to = forms.IntegerField(widget=forms.HiddenInput())

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Penalty
        fields = []

redWine/views.py
# -*- coding: utf-8 -*-
import datetime, re
from operator import itemgetter
from django.http import HttpResponse
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.exceptions import PermissionDenied #change error 
from django.db.models import Q
from .models import Penalty
from .forms import newPenaltyForm
from django.contrib.auth import get_user_model

@login_required
def redWine_home(request):
    try:
        return redWine_com(request, request.user.groups.filter(Q(name="Hovedstyret")|Q(name__endswith="Kom"))[0])
    except(IndexError):
        return render(request, 'index.html', { "error":True, "errorMessage":"You have no active redWine committees!"})

def redWine_com(request, committee):
    User = get_user_model()
    submitted=False
    showDeleted=False
    ownDelete=False
    editedUser=-1
    kom = request.user.groups.filter(name=committee)[:1].get();

    if request.method == 'POST':
        act=str(request.POST['act'])
        form = newPenaltyForm(data=request.POST)
        if act =='add':
            if int(form.data['amount'])<=10 and 1<len(form.data['reason'])<=100:
                #todo: sjekk at man gir til samme komite
                s=Penalty(
                    giver=     request.user,
                    committee= str(form.data['committee'].encode('utf8')),
                    to=        User.objects.get(pk=(int(form.data['to']))),
                    amount=    int(form.data['amount']),
                    reason=    str(form.data['reason'].encode('utf8')),
                    item=      "wine",
                    item_name= "vin"
                    )
                s.save()
                editedUser=int(form.data['to'])
            else:
                return render(request, 'index.html', { "error":True, "errorMessage":"The reason must be between 1 and 100 chars."})
                
        elif 'delete' in act: 
            #filter for koms
            penalty=Penalty.objects.get(pk=int(act.split(" ")[1]))
            if str(penalty.to.username) != str(request.user):
                penalty.deleted=True
                penalty.save()
                editedUser=penalty.to.id

        elif 'nuke' in act:
            #filter for kom
            for penalty in Penalty.objects.filter(to=User.objects.get(pk=int(act.split(" ")[1]))):
                if str(penalty.to.id) != str(request.user.id):
                    penalty.deleted=True
                    penalty.save()
                    editedUser=int(act.split(" ")[1])
                else:
                    ownDelete=True

        elif 'showhidden' in act:
            showDeleted=True
            editedUser=int(act.split(" ")[1])

        else:
            form=newPenaltyForm()

    committees = {} #move total into loop if multiple coms in one page
    total = lambda user: sum([penalty.amount for penalty in user.penalties.filter(deleted=False, committee=com)])
    for com in request.user.groups.filter(Q(name="Hovedstyret")|Q(name__endswith="Kom")):
        if com==kom:
            committees[com] = [(user, total(user)) for user in com.user_set.all()] #wat? wat. sort by total?
            committees[com].sort(key=itemgetter(1),reverse=True)
        else:
            committees[com] = (0,0)

    return render(request, 'index.html', {  
        'committees'   : committees,
        'currCom'      : kom,
        'submittedNew' : submitted,
        'showDeleted'  : showDeleted,
        'editedUser'   : editedUser,
        'ownDelete'    : ownDelete,
        #'form' : form,
        })

redwine/views.py
# -*- coding: utf-8 -*-
import datetime, re
from operator import itemgetter
from django.http import HttpResponse
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.conf import settings
from django.core.exceptions import PermissionDenied #change error 
from django.db.models import Q
from .models import Penalty
from .forms import newPenaltyForm
from django.contrib.auth import get_user_model
from django.db.models import Prefetch
from zoneinfo import ZoneInfo


@login_required
def redwine_home(request):
    try:
        return redwine_com(request, request.user.groups.filter(pk__in=settings.USER_SEARCH_GROUPS)[0])
    except(IndexError):
        return render(request, 'redwine/index.html', { "error":True, "errorMessage":"You have no active redwine committees!"})

def redwine_com(request, committee):
    User = get_user_model()
    submitted=False
    showDeleted=False
    ownDelete=False
    editedUser=-1
    try:
        kom = request.user.groups.filter(name=committee)[:1].get();
    except:                                                             #TODO: handle exception better!
        return render(request, 'redwine/index.html', { 
            "error":True, 
            "errorMessage":"You don't have access to this committee. If you think you should, please contact a sysadmin."
            })

    if request.method == 'POST':
        act=str(request.POST['act'])
        form = newPenaltyForm(data=request.POST)
        if act =='add':
            if int(form.data['amount'])<=10 and 1<len(form.data['reason'])<=100:
                
                # liten artificial block for redwines største misbrukere
                if form.data['committee'] in ("velKom",):
                    giver = int(request.user.id)
                    curfew_map = {
                        2595: "Fredrik",
                        2596: "Pelle",
                    }

                    oslo_timezone = ZoneInfo('Europe/Oslo')
                    current_time_oslo = datetime.datetime.now(oslo_timezone)

                    start_time = current_time_oslo.replace(hour=20, minute=0, second=0, microsecond=0)
                    end_time = current_time_oslo.replace(hour=8, minute=0, second=0, microsecond=0)

                    if (start_time <= current_time_oslo or current_time_oslo < end_time) and giver in curfew_map:
                        return render(request, 'redwine/index.html', { "error":True, "errorMessage":"Leggetid for deg nå {0}".format(
                            curfew_map[giver]
                        )})

                #todo: sjekk at man gir til samme komite
                item=form.data['type'].split(".")
                if len(item)<1:
                    return

                s=Penalty(
                    giver=     request.user,
                    committee= form.data['committee'],
                    to=        User.objects.get(pk=(int(form.data['to']))),
                    amount=    int(form.data['amount']),
                    reason=    form.data['reason'],
                    item=      item[0],
                    item_name= item[1]
                    )
                s.save()
                editedUser=int(form.data['to'])
            else:
                return render(request, 'redwine/index.html', { "error":True, "errorMessage":"The reason must be between 1 and 100 chars."})
                
        elif 'delete' in act: 
            #filter for koms
            penalty=Penalty.objects.get(pk=int(act.split(" ")[1]))
            if str(penalty.to.id) != str(request.user.id):
                penalty.deleted=True
                penalty.save()
                editedUser=penalty.to.id

        elif 'nuke' in act:
            #filter for kom
            for penalty in Penalty.objects.filter(to=User.objects.get(pk=int(act.split(" ")[1]))):
                if str(penalty.to.id) != str(request.user.id):
                    penalty.deleted=True
                    penalty.save()
                    editedUser=int(act.split(" ")[1])
                else:
                    ownDelete=True

        elif 'showhidden' in act:
            showDeleted=True
            editedUser=int(act.split(" ")[1])

        else:
            form=newPenaltyForm()

    committees = {} #move total into loop if multiple coms in one page
    total = lambda user: sum([penalty.amount for penalty in user.penalties.filter(deleted=False, committee=com)])
    by_kom= lambda user: user.penalties.filter(deleted=False, committee=com)
    for com in request.user.groups.filter(pk__in=settings.USER_SEARCH_GROUPS):
        if com==kom:
            
            committees[com] = [(user, total(user), by_kom(user)) for user in com.user_set.all()] 
            committees[com].sort(key=itemgetter(1),reverse=True)
        else:
            committees[com] = (0,0,0)

    return render(request, 'redwine/index.html', {  
        'committees'   : committees,
        'currCom'      : kom,
        'submittedNew' : submitted,
        'showDeleted'  : showDeleted,
        'editedUser'   : editedUser,
        'ownDelete'    : ownDelete,
        #'form' : form,
        })


def total_unflitered(user):
    return sum([penalty.amount for penalty in user.penalties.all()])


def redwine_top(request):
    User = get_user_model()

    # check if in com
    try:
        kom = request.user.groups.filter(pk__in=settings.USER_SEARCH_GROUPS)[:1].get()
    except:                                                             #TODO: handle exception better!
        return render(request, 'redwine/index.html', { 
            "error": True, 
            "errorMessage": "You are not in any commitee"
            })

    committees = {} # move total into loop if multiple coms in one page
    
    kom = "top"
    for com in request.user.groups.filter(pk__in=settings.USER_SEARCH_GROUPS):
        committees[com] = (0, 0, 0)

    penalties = Penalty.objects.filter(amount__lt=9).prefetch_related(
        Prefetch('to', queryset=User.objects.all()),
        Prefetch('giver', queryset=User.objects.all()),
    )

    top = {}
    for penalty in penalties:
        username = penalty.to.username
        if penalty.amount < 9:  # dont count "fake" penalties
            if username not in top:
                top[username] = [penalty.to, penalty.amount, [penalty]]
            else:
                top[username][1] += penalty.amount
                top[username][2].append(penalty)

    top = list(top.values())
    top.sort(key=itemgetter(1), reverse=True)
    if len(top) > 20:
        top = top[:20]

    return render(request, 'redwine/top.html', {  
        'committees'   : committees,
        'currCom'      : kom,
        'top'          : top,
        })

redwine/templates/redwine/base.html
<html version="-//W3C//DTD XHTML 1.1//EN" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="Vinstraffsystem">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Nicolas">
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/redwine.css" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/redwine.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="navbar-brand" href="indextest">RedWine</a>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">
                            <span class="glyphicon glyphicon-user" style="padding-right:17px;"></span>
                            {% if user.is_authenticated %}
                                {{ user.username }}
                            {% else %}
                                <li><a href="admin">Logg Inn</a></li>
                            {% endif %}
                        </a>
                    </li>
                    {%if user.is_staff %}
                        <li>
                            <a href="admin">Adminpanel</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        {% block content %}{% endblock%}
    </div>
</body>
</html>

redwine/templates/redwine/index.html
{% extends "base.html" %}
{% block title %} {{currCom}} - RedWine {% endblock title %}
{% load filters %}
{% block styles %}
{{ block.super }}
<link href="{{ STATIC_URL }}css/redwine.css" rel="stylesheet">
{% endblock %}
{% block content %}
{% include 'redwine/navbar.html' %}
<section id="redwine">
    <div class="container">
        <!--<div id="nyan" class="nyan"></div>-->
        <div class="row">
            {%for kom, users in committees.items %}
            {%ifequal currCom kom %} 
            <div class="col-md-12">
                <div class="page-header">
                    <input type="search" class="search" placeholder="Søk" name="search" id="search">
                    <h2>{{kom}} - Vinstraffer</h2>
                </div>
                <div class="page-header" id="accordion">
                    <table class="table searchtable" id="maintable">
                        <thead>
                            <tr class="center">
                                <th class="left col-md-6"><strong>Navn</strong></th>
                                <th class="col-sm-2 center headerSortDown"><strong>Antall</strong></th>
                                <th class="center"><strong>Sist straffet</strong></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for member, tot, by_kom in users %}
                            <tr data-toggle="collapse" data-target="#{{kom.id}}_{{member.id}}" data-parent="#accordion" class="accordion-toggle center clickable">
                                <td class="nameCell left col-md-6 listname">
                                    <a href="/profile/{{member.username}}/" class="glyphicon glyphicon-user frontIcons"></a>
                                    {{ member.get_full_name }}
                                </td>
                                <td title="{{ tot }} {% ifequal tot 1 %}straff{%else%}straffer{%endifequal%}"
                                    class="col-sm-2 nameCell total">
                                    {% for penalty in member.penalties.all %}
                                        {% if penalty.deleted %}{%else%}
                                            {% ifequal penalty.committee currCom.name %}
                                            {% for penalties in penalty.amount|get_range %}
                                            <img src="/static/img/{{penalty.item}}.png" alt="{{penalty.item_name}}" class="{{penalty.item}}">
                                            {% endfor %}
                                            {% endifequal %}
                                        {%endif%}
                                    {% endfor %}
                                </td>
                                <td class="nameCell">{{ by_kom.latest.date | date:"d M Y H:i" }}</td>
                                <td><span class="glyphicon glyphicon-chevron-down"></span></td>
                            </tr>
                            <tr>
                                <td colspan="4" class="hiddenRow">
                                    <div class="accordian-body collapse elementInfo {% ifequal member.id editedUser %}in{% endifequal %}" id="{{kom.id}}_{{member.id}}">
                                        <div class="row noMargin">
                                            <div class="newCol">
                                                <form class="form-inline addNew" role="form" action="." method="post">
                                                    {% csrf_token %}
                                                    {{ form.non_field_errors }}
                                                    <div class="form-group">
                                                        <div class="col-xs-10">
                                                            <label class="sr-only" for="exampleInputEmail2">Ny Vinstraff</label>
                                                            {{ form.reason.errors }}
                                                            <input type="text"  pattern=".{1,100}" class="form-control" id="id_reason" name="reason" placeholder="Begrunnelse på ny vinstraff">
                                                        </div>
                                                        <div class="addBox col-xs-1">
                                                            {{ form.amount.errors }}
                                                            <select id="select-control" class="form-control" id="type" name="type" style="width: auto !important;">
                                                                <option value="wine.vin">Vin</option>
                                                                <option value="beer.øl">Øl</option>
                                                            </select>
                                                            <select id="select-control" class="form-control" id="amount" name="amount">
                                                            {% for num in "123456789"%}<option{%ifequal num wineString %} nosel {% endifequal %}>{{ num }}</option>{%endfor%}
                                                            </select>
                                                            <input id="id_to" name="to" type="hidden" value="{{ member.id }}">
                                                            <input id="committee" name="committee" type="hidden" value="{{ kom }}">
                                                            <button type="submit" name="act" class="btn btn-success" title="Ny Vinstraff" value="add">
                                                            <span class="glyphicon glyphicon-plus"></span> Ny</button>
                                                        </div>
                                                    </div>
                                            </div>
                                        </div>
                                        {%for penalty in member.penalties.all %}
                                        {% ifequal penalty.committee currCom.name %}
                                        {% ifequal penalty.deleted showDeleted %}
                                        <div class="row noMargin">
                                            <hr>
                                            <div class="col-md-6">
                                            <blockquote>
                                                <p class="breakword">{{ penalty.reason }}</p> 
                                                <small>Gitt av <a href="/profile/{{penalty.giver.username}}/"><cite title="Brukerprofil">{{ penalty.giver }}</cite></a></small>
                                            </blockquote>
                                            </div>
                                            <div title="{{ penalty.amount }} {% ifequal penalty.amount 1 %}{{penalty.item_name}}straff{%else%}{{penalty.item_name}}straffer{%endifequal%}" class="col-sm-2 nameCell center noLeftPadd">
                                                {% for vin in penalty.amount|get_range %}
                                                <img src="/static/img/{{penalty.item}}.png" alt="{{penalty.item_name}}" class="{{penalty.item}}">
                                                {% endfor %}
                                            </div>
                                            <div title="Vinstraff gitt {{ penalty.date | date:'d M Y H:i' }}" class="col-sm-2 nameCell minCell">
                                                {{penalty.date | date:"d M Y H:i"}}
                                            </div>
                                            <div class="col-sm-2">
                                                <span class="rightFloat">
                                                    {%if penalty.deleted %}
                                                    <button type="button" name="act" class="btn" title="Slettet straff" value="">
                                                        <span class="glyphicon glyphicon-ban-circle"></span> 
                                                        Slettet
                                                    </button>
                                                    {% else %}
                                                    <button type="submit" name="act" class="btn btn-danger" title="Slett" value="delete {{ penalty.pk }}">
                                                        <span class="glyphicon glyphicon-ban-circle"></span> 
                                                        Slett
                                                    </button>
                                                    {% endif %}
                                                </span>
                                            </div>
                                        </div>
                                        {% endifequal %}
                                        {% endifequal %}
                                        {% endfor %}
                                        <div class="row noMargin">
                                            <hr>
                                            <div class="moreCell">
                                                {%if showDeleted %}
                                                <button type="submit" name="act" class="btn btn-warning" title="Vis Slettede Straffer" value="">
                                                <span class="glyphicon glyphicon-eye-close"></span> Skjul Slettede</button>
                                                {% else %}
                                                <button type="submit" name="act" class="btn btn-warning" title="Vis Slettede Straffer" value="showhidden {{ member.id }}">
                                                <span class="glyphicon glyphicon-trash"></span> Vis Slettede</button>
                                                {% endif %}     
                                                <button type="submit" name="act" class="btn permabutton" title="Annuler alle penalties" value="nuke {{ member.id }}">
                                                <span class="glyphicon glyphicon-fire"></span> Slett Alle</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                {%endfor%}
                </tbody>
            </table>
        </div>
        </div>
        {% endifequal %}
        {% endfor %}
        {% if error %}
        <div class="page-header">Error: {{errorMessage}}</div>
        {% endif %}
    </div>
</section>
{% endblock content %}
{% block js %}
{{ block.super }}
<script src="{{ STATIC_URL }}js/jquery.filtertable.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery.tablesorter.min.js"></script> 
<script>
    $(document).ready(function() {
            $("#maintable").tablesorter(); 
            $('table').filterTable({
              inputSelector:"#search"
            });
            {%if ownDelete %}
            //$(document.getElementById("nyan")).toggleClass( "goNyan" );
            {% endif %}
        });
</script>
{% endblock %}

redwine/templates/redwine/navbar.html
<nav class="subnavbar">
    <div class="container">
        <ul>
            {%for kom, users in committees.items %}
                {%ifequal currCom kom %}
                    <li class="top-menu-link active">
                        <a class="active" href="/redwine/{{kom}}">{{ kom }}</a>
                    </li>
                {%else%}
                    <li class="top-menu-link">
                        <a class="" href="/redwine/{{kom}}">{{ kom }}</a>
                    </li>
                {%endifequal%}
            {% endfor %}
            {%if top %}
                <li class="top-menu-link active">
                    <a class="active" href="/redwine/top">Wall of Shame</a>
                </li>
            {%else%}
                <li class="top-menu-link">
                    <a class="" href="/redwine/top">Wall of Shame</a>
                </li>
            {%endif%}
            
        </ul>
    </div>
</nav>